server:
  port: 8092


spring:

  kafka:
    bootstrap-servers: ${KF_BROKER:localhost:9092}
    topic:
      orchestrator: orchestrator
      inventory-success: inventory-success
      inventory-fail: inventory-fail
    consumer:
      group-id: inventory-group
      auto-offset-reset: latest

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${HOST:localhost}:${PORT:5434}/${DATA_NAME:inventory-db}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      apache:
        kafka: OFF